[[plugins]]
repo = 'hynek/vim-python-pep8-indent'
on_ft = ['python', 'python3']

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = ['python', 'python3']

[[plugins]]
repo = 'scrooloose/syntastic'
on_ft = ['python', 'python3']
hook_add = 'let g:syntastic_python_checkers = ["flake8"]'
